[workspace]
members = [
"rustbot",
"shared",
"mod_admin",
"mod_core",
"mod_dice",
"mod_test",
]

[replace]
"openssl:0.9.24" = { git = "https://github.com/ishitatsuyuki/rust-openssl", branch = "0.9.x" }
