[package]
name = "mod_dice"
version = "0.1.0"
authors = ["GinjaNinja32 <ginjaninja32@gmail.com>"]

[lib]
crate_type = ["dylib"]

[dependencies]
shared = { path = "../shared" }
nom = "^4.2"
rand = "0.6.5"
