[package]
name = "mod_core"
version = "0.1.0"
authors = ["GinjaNinja32 <ginjaninja32@gmail.com>"]
edition = "2018"

[lib]
crate_type = ["dylib"]

[dependencies]
rustbot = { path = "../rustbot" }
log = "0.4"
