[package]
name = "mod_admin"
version = "0.1.0"
authors = ["GinjaNinja32 <ginjaninja32@gmail.com>"]
edition = "2018"

[lib]
crate_type = ["dylib"]

[dependencies]
postgres = { version = "0.17", features = ["with-serde_json-1"] }
rustbot = { path = "../rustbot" }
serde_json = "1.0.39"
