[package]
name = "mod_admin"
version = "0.1.0"
authors = ["GinjaNinja32 <ginjaninja32@gmail.com>"]

[lib]
crate_type = ["dylib"]

[dependencies]
postgres = { version = "0.15.2", features = ["with-serde_json"] }
rustbot = { path = "../rustbot" }
serde_json = "1.0.39"
