[package]
name = "shared"
version = "0.1.0"
authors = ["GinjaNinja32 <ginjaninja32@gmail.com>"]

[lib]
crate-type = ["dylib"]

[dependencies]
rusqlite = { version = "0.16.0", features = ["bundled"] }
