[package]
name = "rustbot"
version = "0.1.0"
authors = ["GinjaNinja32 <ginjaninja32@gmail.com>"]

[dependencies]
libloading = "0.5.0"
irc = "0.13.6"
toml = "0.4.10"
serde = "1.0.87"
serde_derive = "1.0.87"
shared = { path = "../shared" }
